{{- if and .Values.enbw.keySeed (not .Values.enbw.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-enbw" (include "voltpilot.fullname" .) }}
  labels:
    {{- include "voltpilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.enbw.secretKey }}: {{ .Values.enbw.keySeed | quote }}
{{- end }}
